name: CI

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - run: cargo fmt --check
      - run: cargo clippy --all-targets
      - run: cargo nextest run --no-tests=pass
